# Generated by Django 2.1.10 on 2019-10-05 15:52

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.IntegerField(choices=[(0, 'Other'), (1, 'University'), (2, 'College'), (3, 'Company'), (4, 'Private')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_confirmed', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='academics', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('short_bio', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='short_bio')),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='bio')),
                ('address', models.CharField(blank=True, default='', max_length=128, verbose_name='address')),
                ('zip', models.CharField(blank=True, default='', max_length=20, verbose_name='zip')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='city')),
                ('country', models.CharField(blank=True, default='', max_length=100, verbose_name='country')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='phone')),
                ('website', models.URLField(blank=True, default='http://academycity.org', verbose_name='website')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d/')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Institution')),
            ],
        ),
    ]
