# Generated by Django 2.1.10 on 2019-10-05 23:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='short_bio',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='short_bio'),
        ),
    ]
