# Generated by Django 2.1.10 on 2019-11-12 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191006_0245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created'], 'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
    ]
