# Generated by Django 3.0.10 on 2021-04-24 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('target_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('target_ct', models.ForeignKey(blank=True, limit_choices_to={'model__in': ('fabhouseafrica', 'bizland')}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webcompanies', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'web_companies',
                'verbose_name_plural': 'web_companies',
            },
        ),
    ]
