# Generated by Django 3.0.10 on 2021-05-11 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('webcompanies', '0004_auto_20210510_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcompanies',
            name='domain',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='webcompanies',
            name='target_ct',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('fabhoseafricaweb', 'bizlandweb', 'radiusfoodweb', 'countries')}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webcompanies', to='contenttypes.ContentType'),
        ),
    ]
