# Generated by Django 3.1.11 on 2021-05-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000)),
                ('institution_name', models.CharField(max_length=100, null=True)),
                ('institution_short_description', models.CharField(max_length=500, null=True)),
                ('youtube_video_address', models.CharField(max_length=500, null=True)),
                ('address1', models.CharField(max_length=100, null=True)),
                ('address2', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'institution',
                'verbose_name_plural': 'institutions',
                'ordering': ['order'],
            },
        ),
    ]
