# Generated by Django 3.1.11 on 2021-05-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_popular',
            field=models.BooleanField(default=True),
        ),
    ]
