# Generated by Django 3.1.11 on 2021-05-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20210528_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000)),
                ('news_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('news_type', models.CharField(max_length=100, null=True)),
                ('news_type_description', models.CharField(max_length=100, null=True)),
                ('news_title', models.CharField(max_length=100, null=True)),
                ('news_description', models.CharField(max_length=500, null=True)),
                ('is_popular', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
                'ordering': ['order'],
            },
        ),
    ]
