# Generated by Django 3.1.11 on 2021-06-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Programs/')),
                ('Program_title', models.CharField(max_length=100, null=True)),
                ('Program_description', models.CharField(max_length=500, null=True)),
                ('is_popular', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['order'],
            },
        ),
    ]
