# Generated by Django 3.1.11 on 2021-06-02 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_programs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programs',
            old_name='Program_description',
            new_name='program_description',
        ),
        migrations.RenameField(
            model_name='programs',
            old_name='Program_title',
            new_name='program_title',
        ),
    ]
