# Generated by Django 3.1.11 on 2021-06-04 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_auto_20210604_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionweb',
            name='image',
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='phrase/')),
                ('persons_phrase', models.CharField(max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('institution_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='education.institutionweb')),
            ],
            options={
                'verbose_name': 'phrase',
                'verbose_name_plural': 'phrases',
                'ordering': ['order'],
            },
        ),
    ]
