# Generated by Django 3.1.11 on 2021-06-04 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_auto_20210604_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='persons_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='AdditionalTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='phrase/')),
                ('topic_description', models.CharField(max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('institution_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='education.institutionweb')),
            ],
            options={
                'verbose_name': 'topic',
                'verbose_name_plural': 'topics',
                'ordering': ['order'],
            },
        ),
    ]
