# Generated by Django 3.1.11 on 2021-06-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_auto_20210604_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionweb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='institution/'),
        ),
    ]
