# Generated by Django 3.1.11 on 2021-06-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_institutionweb_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionweb',
            name='image',
        ),
        migrations.AddField(
            model_name='institutionweb',
            name='institution_image',
            field=models.ImageField(blank=True, null=True, upload_to='institution/'),
        ),
    ]
