# Generated by Django 3.1.11 on 2021-06-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0015_auto_20210604_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionweb',
            name='institution_short_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='institutionweb',
            name='youtube_video_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
