# Generated by Django 3.1.11 on 2021-06-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0016_auto_20210604_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionweb',
            name='footer_image',
            field=models.ImageField(blank=True, null=True, upload_to='institution/'),
        ),
        migrations.AddField(
            model_name='institutionweb',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='institution/'),
        ),
    ]
