# Generated by Django 3.1.11 on 2021-06-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0017_auto_20210604_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionweb',
            name='footer_phrase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
