# Generated by Django 3.1.11 on 2021-06-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0018_institutionweb_footer_phrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionweb',
            name='github_domain_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
