# Generated by Django 3.1.11 on 2021-06-15 16:35

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('education', '0019_institutionweb_github_domain_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='partner_description', to='cms.placeholder'),
        ),
    ]
