# Generated by Django 3.1.11 on 2021-06-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0020_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_description',
        ),
    ]
