# Generated by Django 3.1.11 on 2021-06-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0022_auto_20210616_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
