# Generated by Django 3.1.11 on 2021-05-27 02:04

from django.db import migrations, models
import django.db.models.deletion
import highschooledu.apps.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Debug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(choices=[(0, 'Other'), (1, 'General Ledger')], default=1)),
                ('number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AdjectivesValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', highschooledu.apps.core.fields.OrderField(blank=True, default=1)),
                ('value', models.CharField(max_length=50)),
                ('adjective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.adjectives')),
            ],
        ),
    ]
