# Generated by Django 3.1.11 on 2021-06-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckCashingWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('domain_name', models.CharField(blank=True, max_length=100, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='checkcashing/')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='checkcashing/')),
            ],
            options={
                'verbose_name': 'check cashing',
                'verbose_name_plural': 'check cashing',
                'ordering': ['order'],
            },
        ),
    ]
