# Generated by Django 3.1.11 on 2021-06-18 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkcashingchicago', '0002_auto_20210617_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='location/')),
                ('location_heading', models.CharField(max_length=100, null=True)),
                ('location_info', models.CharField(max_length=100, null=True)),
                ('data_ajax_id', models.IntegerField(default=0)),
                ('grid_loop', models.IntegerField(default=0)),
                ('grid_parity', models.CharField(max_length=10, null=True)),
                ('south_suburbs_sort', models.CharField(max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('check_cashing_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='checkcashingchicago.checkcashingweb')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'ordering': ['order'],
            },
        ),
    ]
