# Generated by Django 3.1.11 on 2021-06-18 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkcashingchicago', '0004_auto_20210618_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='currency/')),
                ('currency_header', models.CharField(max_length=100, null=True)),
                ('currency_description', models.CharField(max_length=500, null=True)),
                ('image_id', models.IntegerField(default=0)),
                ('currency_loop', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('check_cashing_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='checkcashingchicago.checkcashingweb')),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencies',
                'ordering': ['order'],
            },
        ),
    ]
