# Generated by Django 3.1.11 on 2021-06-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkcashingchicago', '0005_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='grid_loop',
        ),
        migrations.RemoveField(
            model_name='location',
            name='grid_parity',
        ),
        migrations.AddField(
            model_name='currency',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='currency/'),
        ),
        migrations.AddField(
            model_name='location',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='location/'),
        ),
        migrations.AddField(
            model_name='location',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
