# Generated by Django 3.1.11 on 2021-06-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkcashingchicago', '0008_auto_20210619_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(max_length=250, null=True),
        ),
    ]
