# Generated by Django 3.1.11 on 2021-06-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkcashingchicago', '0011_remove_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.ManyToManyField(related_name='services', to='checkcashingchicago.Location'),
        ),
    ]
