# Generated by Django 3.1.11 on 2021-06-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkcashingchicago', '0013_auto_20210621_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkcashingweb',
            name='application_for_employment',
            field=models.FileField(blank=True, null=True, upload_to='checkcashing/'),
        ),
        migrations.AddField(
            model_name='checkcashingweb',
            name='check_cashing_application',
            field=models.FileField(blank=True, null=True, upload_to='checkcashing/'),
        ),
        migrations.AddField(
            model_name='checkcashingweb',
            name='copy_right_year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
