# Generated by Django 3.1.11 on 2021-06-22 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkcashingchicago', '0018_auto_20210621_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkcashingweb',
            name='contact_us_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ContactUsMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('message', models.TextField(null=True)),
                ('check_cashing_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='checkcashingchicago.checkcashingweb')),
            ],
            options={
                'verbose_name': 'contact_us_message',
                'verbose_name_plural': 'contact_us_messages',
            },
        ),
    ]
