# Generated by Django 3.1.11 on 2021-06-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkcashingchicago', '0019_auto_20210622_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
