# Generated by Django 3.1.11 on 2021-06-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkcashingchicago', '0020_partner_partner_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='working_hours1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='working_hours2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='working_hours3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='working_hours4',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
