# Generated by Django 3.1.11 on 2021-06-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkcashingchicago', '0021_auto_20210623_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='working_hours1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='working_hours2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='working_hours3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='working_hours4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
