# Generated by Django 3.1.11 on 2021-06-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkcashingchicago', '0022_auto_20210623_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_detail_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
