# Generated by Django 3.1.11 on 2021-06-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkcashingchicago', '0024_auto_20210623_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkcashingweb',
            name='members_password',
            field=models.CharField(default='101', max_length=100),
        ),
    ]
