# Generated by Django 3.1.11 on 2021-06-25 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkcashingchicago', '0025_checkcashingweb_members_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('check_cashing_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='document_categories', to='checkcashingchicago.checkcashingweb')),
            ],
            options={
                'verbose_name': 'document_category',
                'verbose_name_plural': 'document_categories',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='checkcashing/documents')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_documents', to='checkcashingchicago.documentcategory')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
            },
        ),
    ]
