# Generated by Django 2.1.10 on 2021-06-29 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='contacts/')),
                ('phone1', models.CharField(max_length=100, null=True)),
                ('phone2', models.CharField(max_length=100, null=True)),
                ('email1', models.CharField(max_length=100, null=True)),
                ('email2', models.CharField(max_length=100, null=True)),
                ('address1', models.CharField(max_length=100, null=True)),
                ('address2', models.CharField(max_length=100, null=True)),
                ('is_popular', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Porject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('heading', models.CharField(max_length=100, null=True)),
                ('sub_heading', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('is_popular', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000, null=True)),
                ('portfolio_name', models.CharField(blank=True, max_length=100, null=True)),
                ('domain_name', models.CharField(blank=True, max_length=100, null=True)),
                ('welcome_phrase1', models.CharField(blank=True, max_length=100, null=True)),
                ('welcome_phrase2', models.CharField(blank=True, max_length=100, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('logo_name', models.CharField(blank=True, max_length=100, null=True)),
                ('footer_phrase', models.CharField(blank=True, max_length=100, null=True)),
                ('Short_description', models.CharField(blank=True, max_length=200, null=True)),
                ('portfolio_link', models.CharField(max_length=100, null=True)),
                ('copyright_year', models.CharField(blank=True, max_length=100, null=True)),
                ('copyright_phrase', models.CharField(blank=True, max_length=100, null=True)),
                ('service_title', models.CharField(blank=True, max_length=100, null=True)),
                ('service_phrase', models.CharField(blank=True, max_length=100, null=True)),
                ('project_title', models.CharField(blank=True, max_length=100, null=True)),
                ('about_title', models.CharField(blank=True, max_length=100, null=True)),
                ('about_phrase', models.CharField(blank=True, max_length=100, null=True)),
                ('about_subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('about_link', models.CharField(blank=True, max_length=100, null=True)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('contact_title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'portfolio',
                'verbose_name_plural': 'portfolios',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('heading', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('is_popular', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('portfolio_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='portfolio.PortfolioWeb')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='porject',
            name='portfolio_web',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.PortfolioWeb'),
        ),
        migrations.AddField(
            model_name='contact',
            name='portfolio_web',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='portfolio.PortfolioWeb'),
        ),
    ]
