# Generated by Django 2.1.10 on 2021-06-30 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('heading', models.CharField(max_length=100, null=True)),
                ('sub_heading', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('portfolio_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.PortfolioWeb')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='porject',
            name='portfolio_web',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_popular',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_popular',
        ),
        migrations.DeleteModel(
            name='Porject',
        ),
    ]
