# Generated by Django 2.1.10 on 2021-07-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210630_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioweb',
            old_name='portfolio_name',
            new_name='contact_address1',
        ),
        migrations.AddField(
            model_name='portfolioweb',
            name='contact_address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolioweb',
            name='contact_email1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolioweb',
            name='contact_email2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolioweb',
            name='contact_phone1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolioweb',
            name='contact_phone2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolioweb',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolioweb',
            name='second_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
