# Generated by Django 2.1.10 on 2021-07-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210701_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioweb',
            old_name='first_name',
            new_name='portfolio_name',
        ),
        migrations.RemoveField(
            model_name='portfolioweb',
            name='second_name',
        ),
    ]
