# Generated by Django 2.1.10 on 2021-07-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210702_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='portfolio_web',
        ),
        migrations.AddField(
            model_name='portfolioweb',
            name='Be_image',
            field=models.ImageField(blank=True, null=True, upload_to='footer/'),
        ),
        migrations.AddField(
            model_name='portfolioweb',
            name='address_image',
            field=models.ImageField(blank=True, null=True, upload_to='contacts/'),
        ),
        migrations.AddField(
            model_name='portfolioweb',
            name='email_image',
            field=models.ImageField(blank=True, null=True, upload_to='contacts/'),
        ),
        migrations.AddField(
            model_name='portfolioweb',
            name='facebook_image',
            field=models.ImageField(blank=True, null=True, upload_to='footer/'),
        ),
        migrations.AddField(
            model_name='portfolioweb',
            name='instragram_image',
            field=models.ImageField(blank=True, null=True, upload_to='footer/'),
        ),
        migrations.AddField(
            model_name='portfolioweb',
            name='phone_image',
            field=models.ImageField(blank=True, null=True, upload_to='contacts/'),
        ),
        migrations.AddField(
            model_name='portfolioweb',
            name='twitter_image',
            field=models.ImageField(blank=True, null=True, upload_to='footer/'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
