# Generated by Django 2.1.10 on 2021-07-07 12:29

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('portfolio', '0006_auto_20210707_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioweb',
            name='logo_name',
        ),
        migrations.AddField(
            model_name='portfolioweb',
            name='resume',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='resume', to='cms.Placeholder'),
        ),
    ]
